flutter_native_splash:
  web: false
  color: "#ffffff"
  color_dark: "#103157"
  image: "D:/projects/iraq electro/flutter/IraqElectro/android/app/src/main/res/drawable-night/background.png"
  image_dark: "D:/projects/iraq electro/flutter/IraqElectro/android/app/src/main/res/drawable-night/background.png"
  branding: "D:/projects/iraq electro/13.png"
  branding_dark: "D:/projects/iraq electro/14.png"
