flutter_native_splash:
  web: false
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: "C:/Users/ARAS STORE/Desktop/photo_2023-01-19_10-57-37.png"
  image_dark: "C:/Users/ARAS STORE/Desktop/dark.png"


